/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author luanb
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_nboleta = new javax.swing.JTextField();
        txt_mostrar = new javax.swing.JTextField();
        btn_mostrar = new javax.swing.JButton();
        txt_mostrar1 = new javax.swing.JTextField();
        txt_mostrar2 = new javax.swing.JTextField();
        txt_mostrar3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jLabel2.setText("Numero de Boleta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txt_nboleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nboletaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nboleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 30));
        getContentPane().add(txt_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 30));

        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));
        getContentPane().add(txt_mostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));
        getContentPane().add(txt_mostrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));
        getContentPane().add(txt_mostrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 200, 30));

        jLabel3.setText("Ingresa tu numero de boleta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel6.setText("Apellido Materno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel5.setText("Apellido Paterno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conexion/imagenes/8911ff72f741ec73f6606d164e553491.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    Formulario formulario = new Formulario();
    formulario.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void txt_nboletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nboletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nboletaActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
     String boleta,nombre,ap,am,nb;
     
     try {
         boleta = txt_nboleta.getText();
         System.out.println(boleta);
        conexion conec = new conexion();
        Connection con = conec.conexion();
        String consultar ="SELECT * FROM registro WHERE noboleta=?";
        PreparedStatement consu = con.prepareStatement(consultar);
        consu.setString(1, boleta);
        ResultSet rs = consu.executeQuery();
        System.out.println(rs);
        
        
        if(rs.next()){
            nombre=rs.getString(1);
            ap=rs.getString(2);
            am=rs.getString(3);
            nb=rs.getString(4);
            txt_mostrar1.setText(nombre);
            txt_mostrar2.setText(ap);
            txt_mostrar3.setText(am);
            txt_mostrar.setText(nb);
            
            System.out.println(nombre);
            System.out.println("Los valores han sido recolectados"); 
            }
        else{
        lbl_error.setText("El usuario no existe");
        txt_mostrar1.setText("");
        txt_mostrar2.setText("");
        txt_mostrar3.setText("");
        txt_mostrar.setText("");
            
        }
        
        }
         
         
        
        
     
        catch(SQLException e){
           System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Formulario formulario = new Formulario();
    formulario.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JTextField txt_mostrar;
    private javax.swing.JTextField txt_mostrar1;
    private javax.swing.JTextField txt_mostrar2;
    private javax.swing.JTextField txt_mostrar3;
    private javax.swing.JTextField txt_nboleta;
    // End of variables declaration//GEN-END:variables
}
